#!/bin/bash

# only supported on UNIX systems

filename="${!#}"
args="${@:1:$(($# - 1 ))}"

python3 ~/desktop/coding/python/pytocpp/main.py --no-out "$args" -o /tmp/pytocpp_temp.cpp "$filename" || exit 1
g++ -std=c++23 -o /tmp/temp_exec.out /tmp/pytocpp_temp.cpp || exit 1
chmod +x /tmp/temp_exec.out || exit 1
/tmp/temp_exec.out || exit 1
rm /tmp/temp_exec.out
rm /tmp/pytocpp_temp.cpp
exit 0