"""
Contains constants specifying which types are valid for which kind of operation
"""

SLICE_EXPRESSION_ALLOWED_TYPES = ("int",)
CONDITIONAL_EXPRESSION_LOGICAL_OPERATOR_ALLOWED_TYPES = ("bool",)
CONDITIONAL_EXPRESSION_CONDTIONAL_OPERATOR_AllOWED_TYPES = ("int", "float")
CONDITIONAL_EXPRESSION_DEQU_ALLOWED_TYPES = ("str", "bool", "list")
BINOP_EXPRESSION_BASE_ALLOWED_TYPES = ("int", "float")
BINOP_EXPRESSION_PLUS_ALLOWED_TYPES = ("str", "list")
BINOP_EXPRESSION_MUL_ALLOWED_TYPES = ("str",)
BINOP_EXPRESSION_MOD_ALLOWED_TYPES = ("int",)
UNOP_EXPRESSION_SUB_ALLOWED_TYPES = ("int", "float")
UNOP_EXPRESSION_NOT_ALLOWED_TYPES = ("bool",)